### ISSUE TITLE
디자인까지 신경써서 잘 만드셨네요

### ISSUE THREAD

**Issue by dam-lee** [changchanghwang/hanghae_nodejs#4]
디자인 색감이 살짝 부족한 것 같아요
분명히 회색 배경으로 해달라고 요청 드렸는데 아직도 노란색 디자인이더라구요
피드백 반영을 조금 더 신경써주셨으면 좋겠어요😊
백엔드분들이 css 까지 직접 잘 하셔서 프론트로서 조금 부담스럽습니다. css 조금만 못해주세요😊
프론트 에러 공격도 조금만 덜 해주시면 감사하겠습니다 백엔드 분들 무서워요🙏🙏

**Comment by changchanghwang** [comment]
> 디자인 색감이 살짝 부족한 것 같아요 분명히 회색 배경으로 해달라고 요청 드렸는데 아직도 노란색 디자인이더라구요 피드백 반영을 조금 더 신경써주셨으면 좋겠어요😊 백엔드분들이 css 까지 직접 잘 하셔서 프론트로서 조금 부담스럽습니다. css 조금만 못해주세요😊 프론트 에러 공격도 조금만 덜 해주시면 감사하겠습니다 백엔드 분들 무서워요🙏🙏
